// <auto-generated />
namespace MVCATM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pin));
        
        string IMigrationMetadata.Id
        {
            get { return "201811110825461_pin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
